# Generated by Django 4.2.7 on 2024-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
