# Generated by Django 4.2.7 on 2024-06-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_quantity_inventory_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.store'),
            preserve_default=False,
        ),
    ]
