# Generated by Django 4.2.7 on 2024-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sale_seller_sale_price_sale_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='request_source',
            field=models.CharField(choices=[('Store', 'Store'), ('Product', 'Product')], default='Store', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
