# Generated by Django 4.2.7 on 2024-06-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contract_request_source_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
    ]
