# Generated by Django 4.2.7 on 2024-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_inventory_quantity_sold_inventory_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
