# Generated by Django 4.2.7 on 2024-06-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SP', 'Spam'), ('AB', 'Abuse'), ('IC', 'Inappropriate Content'), ('OT', 'Other'), ('SC', 'Scam')], max_length=2)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('UR', 'Under Review'), ('RS', 'Resolved'), ('DS', 'Dismissed')], default='PD', max_length=2)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='main.normaluser')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='main.normaluser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reported_by', 'reported_user', 'reason')},
            },
        ),
    ]
