# Generated by Django 4.2.7 on 2024-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SP', 'Spam'), ('AB', 'Abuse'), ('IC', 'Inappropriate Content'), ('OT', 'Other'), ('SC', 'Scam')], default='AB', max_length=2),
        ),
    ]
